<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
    <NoWarn>$(NoWarn);NU1507</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="AspNet.Security.OAuth.Kook" Version="10.0.0" />
    <PackageVersion Include="coverlet.collector" Version="10.0.1" />
    <PackageVersion Include="Fluid.Core" Version="2.40.0" />
    <PackageVersion Include="MassTransit" Version="8.5.10" />
    <PackageVersion Include="MassTransit.Extensions.DependencyInjection" Version="7.3.1" />
    <PackageVersion Include="Meziantou.Polyfill" Version="1.0.165" />
    <PackageVersion Include="Microsoft.Extensions.Configuration" Version="10.0.12" />
    <PackageVersion Include="Microsoft.Extensions.DependencyInjection" Version="10.0.12" />
    <PackageVersion Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.12" />
    <PackageVersion Include="Microsoft.Extensions.Hosting" Version="10.0.12" />
    <PackageVersion Include="Microsoft.Extensions.Hosting.Abstractions" Version="10.0.12" />
    <PackageVersion Include="Microsoft.Extensions.Http" Version="10.0.12" />
    <PackageVersion Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="10.0.12" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.10.0" />
    <PackageVersion Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.3" />
    <PackageVersion Include="Microsoft.SourceLink.GitHub" Version="10.0.401" />
    <PackageVersion Include="NSubstitute" Version="6.2.0" />
    <PackageVersion Include="Serilog" Version="4.4.0" />
    <PackageVersion Include="Serilog.AspNetCore" Version="10.0.0" />
    <PackageVersion Include="Serilog.Extensions.Hosting" Version="10.0.0" />
    <PackageVersion Include="Serilog.Sinks.Console" Version="6.1.1" />
    <PackageVersion Include="System.Collections.Immutable" Version="10.0.12" />
    <PackageVersion Include="System.Collections.Immutable" Version="10.0.12" />
    <PackageVersion Include="System.Collections.Immutable" Version="10.0.12" />
    <PackageVersion Include="System.Linq.Async" Version="7.0.1" />
    <PackageVersion Include="System.Text.Json" Version="10.0.12" />
    <PackageVersion Include="System.Text.Json" Version="10.0.12" />
    <PackageVersion Include="System.Text.Json" Version="10.0.12" />
    <PackageVersion Include="System.Threading.Channels" Version="10.0.12" />
    <PackageVersion Include="System.Threading.Channels" Version="10.0.12" />
    <PackageVersion Include="System.Threading.Channels" Version="10.0.12" />
    <PackageVersion Include="System.Threading.Channels" Version="10.0.12" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="4.0.0" />
    <PackageVersion Include="xunit.v3" Version="4.0.0" />
  </ItemGroup>
</Project>